"""Stable readiness statuses and blocker codes."""

from enum import StrEnum

NOT_DERIVABLE_FROM_CURRENT_SCHEMA = "NOT_DERIVABLE_FROM_CURRENT_SCHEMA"
COUNTERFACTUAL_PRICE_ONLY_ELIGIBILITY_NOT_DERIVABLE = (
    "COUNTERFACTUAL_PRICE_ONLY_ELIGIBILITY_NOT_DERIVABLE"
)


class LegacyCalibrationReadiness(StrEnum):
    DATA_READY = "LEGACY_CALIBRATION_DATA_READY"
    DATA_INSUFFICIENT = "LEGACY_CALIBRATION_DATA_INSUFFICIENT"
    CLASS_IMBALANCED = "LEGACY_CALIBRATION_CLASS_IMBALANCED"
    PROSPECTIVE_INSUFFICIENT = "LEGACY_CALIBRATION_PROSPECTIVE_INSUFFICIENT"
    SOURCE_INELIGIBLE = "LEGACY_CALIBRATION_SOURCE_INELIGIBLE"


class MvpTradeModelReadiness(StrEnum):
    NOT_READY = "MVP_TRADE_MODEL_NOT_READY"


class PercentageStatus(StrEnum):
    DERIVED = "DERIVED"
    ZERO_DENOMINATOR = "ZERO_DENOMINATOR"
    NOT_DERIVABLE = "NOT_DERIVABLE"


MVP_TRADE_MODEL_BLOCKERS = (
    "EXECUTION_ALIGNED_OUTCOME_POLICY_MISSING",
    "TRANSACTION_COST_POLICY_VALUES_NOT_FROZEN",
    "COST_ADJUSTED_LABEL_POLICY_MISSING",
    "NEXT_OPEN_ENTRY_RESULT_NOT_IMPLEMENTED",
    "FIXED_HOLDING_PERIOD_RESULT_NOT_IMPLEMENTED",
    "MULTI_YEAR_CALENDAR_NOT_AVAILABLE",
    "HISTORICAL_BACKFILL_NOT_VERIFIED",
    "PROSPECTIVE_COLLECTION_NOT_OPERATIONAL",
    "DATA_QUALITY_DECISION_PENDING",
    "VERIFIED_VOLUME_PROVIDER_NOT_SELECTED",
    "SIMPLE_BASELINE_NOT_EVALUATED",
)

PRICE_ONLY_V2_INELIGIBILITY_REASON_ORDER = (
    "FEATURE_LINEAGE_UNAVAILABLE",
    "FEATURE_POLICY_NOT_V1",
    "PRICE_FEATURE_MISSING",
    "PRICE_FEATURE_INVALID",
    "ADJUSTMENT_BASIS_INVALID",
    "COMPLETED_BAR_COUNT_INVALID",
    "QUALITY_STATUS_INELIGIBLE",
    "QUALITY_REASON_INELIGIBLE",
)

LEGACY_RESEARCH_LIMITATION = (
    "The current dataset is suitable only for the legacy positive-forward-close "
    "research question. It is not sufficient evidence for an executable, "
    "cost-adjusted trade model."
)

EXCLUSION_REASON_ORDER = (
    "SCORE_NOT_READY",
    "FEATURE_QUALITY_NOT_READY",
    "VOLUME_DATA_INCOMPLETE",
    "OUTCOME_NOT_FOUND",
    "OUTCOME_NOT_AVAILABLE_AS_OF",
    "LABEL_NOT_FOUND",
    "LABEL_POLICY_MISMATCH",
    "OUTCOME_POLICY_MISMATCH",
    "PROVIDER_MISMATCH",
    "CALENDAR_MISMATCH",
    "MISSING_SCORE",
    "DUPLICATE_SOURCE",
    "OTHER_CONTRACT_FAILURE",
)
