"""Persistable run and item outcomes for the P3 v1 pipeline."""

from enum import StrEnum


class DailyFeaturePipelineItemOutcome(StrEnum):
    READY = "READY"
    DEGRADED = "DEGRADED"
    DATA_INSUFFICIENT = "DATA_INSUFFICIENT"
    NO_DATA = "NO_DATA"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    CALENDAR_ERROR = "CALENDAR_ERROR"
    NOT_ATTEMPTED_BUDGET = "NOT_ATTEMPTED_BUDGET"
    NOT_ATTEMPTED_ABORTED = "NOT_ATTEMPTED_ABORTED"


class DailyFeaturePipelineRunStatus(StrEnum):
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    COMPLETED_WITH_PARTIAL_FAILURES = "COMPLETED_WITH_PARTIAL_FAILURES"
    NO_COMPLETED_SESSION = "NO_COMPLETED_SESSION"
    BUDGET_BLOCKED = "BUDGET_BLOCKED"
    ABORTED_PROVIDER_FATAL = "ABORTED_PROVIDER_FATAL"
