"""Persistable P4A scoring run and item outcomes."""

from enum import StrEnum


class DailyFeatureScoringItemOutcome(StrEnum):
    SCORED_READY = "SCORED_READY"
    SCORED_DEGRADED = "SCORED_DEGRADED"
    SOURCE_ITEM_NOT_SCORABLE = "SOURCE_ITEM_NOT_SCORABLE"
    FEATURE_SNAPSHOT_MISSING = "FEATURE_SNAPSHOT_MISSING"
    FEATURE_SOURCE_MISMATCH = "FEATURE_SOURCE_MISMATCH"
    FEATURE_CONTRACT_INVALID = "FEATURE_CONTRACT_INVALID"
    FEATURE_QUALITY_UNSUPPORTED = "FEATURE_QUALITY_UNSUPPORTED"


class DailyFeatureScoringRunStatus(StrEnum):
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_UNSCORABLE = "COMPLETED_WITH_UNSCORABLE"
    NO_SCORABLE_ITEMS = "NO_SCORABLE_ITEMS"
