"""Canonical Alpaca market-data configuration key names."""

ALPACA_ENABLED_KEY = "AUTO_TRADING_V2_ALPACA_MARKET_DATA_ENABLED"
ALPACA_BASE_URL_KEY = "AUTO_TRADING_V2_ALPACA_MARKET_DATA_BASE_URL"
ALPACA_API_KEY_ID_KEY = "AUTO_TRADING_V2_ALPACA_MARKET_DATA_API_KEY_ID"
ALPACA_API_SECRET_KEY = "AUTO_TRADING_V2_ALPACA_MARKET_DATA_API_SECRET_KEY"
ALPACA_FEED_KEY = "AUTO_TRADING_V2_ALPACA_MARKET_DATA_FEED"
ALPACA_CONNECT_TIMEOUT_KEY = "AUTO_TRADING_V2_ALPACA_MARKET_DATA_CONNECT_TIMEOUT_SECONDS"
ALPACA_READ_TIMEOUT_KEY = "AUTO_TRADING_V2_ALPACA_MARKET_DATA_READ_TIMEOUT_SECONDS"
ALPACA_REQUESTS_PER_MINUTE_KEY = "AUTO_TRADING_V2_ALPACA_MARKET_DATA_REQUESTS_PER_MINUTE"
ALPACA_MAXIMUM_RETRY_ATTEMPTS_KEY = "AUTO_TRADING_V2_ALPACA_MARKET_DATA_MAXIMUM_RETRY_ATTEMPTS"
ALPACA_MAXIMUM_PAGES_KEY = "AUTO_TRADING_V2_ALPACA_MARKET_DATA_MAXIMUM_PAGES"

ALPACA_MARKET_DATA_KEYS = frozenset(
    {
        ALPACA_ENABLED_KEY,
        ALPACA_BASE_URL_KEY,
        ALPACA_API_KEY_ID_KEY,
        ALPACA_API_SECRET_KEY,
        ALPACA_FEED_KEY,
        ALPACA_CONNECT_TIMEOUT_KEY,
        ALPACA_READ_TIMEOUT_KEY,
        ALPACA_REQUESTS_PER_MINUTE_KEY,
        ALPACA_MAXIMUM_RETRY_ATTEMPTS_KEY,
        ALPACA_MAXIMUM_PAGES_KEY,
    }
)
