"""Canonical keys for explicit MSSQL administration configuration."""

MSSQL_ADMIN_URL_KEY = "AUTO_TRADING_V2_MSSQL_ADMIN_URL"
MSSQL_ADMIN_TRANSPORT_KEY = "AUTO_TRADING_V2_MSSQL_ADMIN_TRANSPORT"
MSSQL_TEST_ADMIN_URL_KEY = "AUTO_TRADING_V2_TEST_ADMIN_URL"
MSSQL_TEST_ADMIN_TRANSPORT_KEY = "AUTO_TRADING_V2_TEST_ADMIN_TRANSPORT"

MSSQL_ADMINISTRATION_KEYS = frozenset(
    {
        MSSQL_ADMIN_URL_KEY,
        MSSQL_ADMIN_TRANSPORT_KEY,
        MSSQL_TEST_ADMIN_URL_KEY,
        MSSQL_TEST_ADMIN_TRANSPORT_KEY,
    }
)
