"""Canonical Twelve Data configuration key names."""

TWELVE_DATA_ENABLED_KEY = "AUTO_TRADING_V2_TWELVE_DATA_ENABLED"
TWELVE_DATA_BASE_URL_KEY = "AUTO_TRADING_V2_TWELVE_DATA_BASE_URL"
TWELVE_DATA_API_KEY = "AUTO_TRADING_V2_TWELVE_DATA_API_KEY"
TWELVE_DATA_CONNECT_TIMEOUT_KEY = "AUTO_TRADING_V2_TWELVE_DATA_CONNECT_TIMEOUT_SECONDS"
TWELVE_DATA_READ_TIMEOUT_KEY = "AUTO_TRADING_V2_TWELVE_DATA_READ_TIMEOUT_SECONDS"
TWELVE_DATA_CREDITS_PER_MINUTE_KEY = "AUTO_TRADING_V2_TWELVE_DATA_CREDITS_PER_MINUTE"
TWELVE_DATA_DAILY_CREDIT_BUDGET_KEY = "AUTO_TRADING_V2_TWELVE_DATA_DAILY_CREDIT_BUDGET"
TWELVE_DATA_MAXIMUM_RETRY_ATTEMPTS_KEY = "AUTO_TRADING_V2_TWELVE_DATA_MAXIMUM_RETRY_ATTEMPTS"
TWELVE_DATA_MAXIMUM_REQUESTS_KEY = "AUTO_TRADING_V2_TWELVE_DATA_MAXIMUM_REQUESTS_PER_OPERATION"

TWELVE_DATA_KEYS = frozenset(
    {
        TWELVE_DATA_ENABLED_KEY,
        TWELVE_DATA_BASE_URL_KEY,
        TWELVE_DATA_API_KEY,
        TWELVE_DATA_CONNECT_TIMEOUT_KEY,
        TWELVE_DATA_READ_TIMEOUT_KEY,
        TWELVE_DATA_CREDITS_PER_MINUTE_KEY,
        TWELVE_DATA_DAILY_CREDIT_BUDGET_KEY,
        TWELVE_DATA_MAXIMUM_RETRY_ATTEMPTS_KEY,
        TWELVE_DATA_MAXIMUM_REQUESTS_KEY,
    }
)
