"""Persistable P4B.1 observation modes, run statuses, and item outcomes."""

from enum import StrEnum


class OutcomeObservationMode(StrEnum):
    PROSPECTIVE = "PROSPECTIVE"
    RETROSPECTIVE_REPLAY = "RETROSPECTIVE_REPLAY"


class DailyFeatureOutcomeObservationRunItemOutcome(StrEnum):
    OUTCOME_CREATED = "OUTCOME_CREATED"
    OUTCOME_ALREADY_EXISTS = "OUTCOME_ALREADY_EXISTS"
    NOT_MATURED = "NOT_MATURED"
    FUTURE_BARS_INCOMPLETE = "FUTURE_BARS_INCOMPLETE"
    SOURCE_ITEM_NOT_ELIGIBLE = "SOURCE_ITEM_NOT_ELIGIBLE"
    SOURCE_CHAIN_INVALID = "SOURCE_CHAIN_INVALID"
    FUTURE_BAR_CONTRACT_INVALID = "FUTURE_BAR_CONTRACT_INVALID"
    CALENDAR_OUT_OF_COVERAGE = "CALENDAR_OUT_OF_COVERAGE"


class DailyFeatureOutcomeObservationRunStatus(StrEnum):
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_PENDING = "COMPLETED_WITH_PENDING"
    COMPLETED_WITH_GAPS = "COMPLETED_WITH_GAPS"
    NO_ELIGIBLE_ITEMS = "NO_ELIGIBLE_ITEMS"
    CALENDAR_OUT_OF_COVERAGE = "CALENDAR_OUT_OF_COVERAGE"
